 &PRT zrot=.true., ztran=.true., zlin=.true., ztheta=.FALSE., zr2r1=.FALSE., ZP1D=.false,
ZP2D=.false., ZEMBED=.false., zpfun=.true. /
    3
   30    2   40   45 1000 1500    1    2   16
        HCN: J=2 calculation

    1.007825035          12.0                14.003074002
    1.007825035          12.0                14.003074002
       45000.0
         2.3                   29.0             0.0105
         3.2                    5.0               0.004





































