 &PRT zrot=.true., ztran=.true.,  zlin=.true.,  zcut=.false., zperp=.true./
    3
   28    1  100   40  500 2500   -2    0         0
 H3+: RADAU COORD Z-PERP EMBEDDING
                                        
      1.007537200         1.007537200           1.007537200
      1.007537200         1.007537200           1.007537200
     0.00000            61452.894720
       1.80                0.07                0.0118
       1.80                0.07                0.0118






















