 &PRT  zrot=.true.,  zlin=.true., ztran=.true., zpfun=.true., /
    3
   21    2  150   40  500  500   -2    2    0    0
 WATER: RADAU SYMMETRISED COORDINATES
                                                                          
        1.007825           1.007825            15.990726
        1.007825           1.007825            15.990726
        2.55                0.25                0.007    
        2.55                0.25                0.007
































